FROM python:3.7.3-alpine as base

FROM base as builder

RUN mkdir /install

# Because of this bug: https://github.com/psycopg/psycopg2/issues/684
RUN apk add postgresql-dev
RUN apk add gcc
RUN apk add python3-dev
RUN apk add musl-dev
RUN apk add libffi-dev

# Install gunicorn
RUN python3 -m pip install --upgrade pip
RUN pip3 install --install-option="--prefix=/install" gunicorn

# Copy over and install our package
COPY dist/buildings_api-0.1.0.tar.gz /build/buildings_api-0.1.0.tar.gz
RUN pip3 install --install-option="--prefix=/install" /build/buildings_api-0.1.0.tar.gz

FROM base

# Configure container start
COPY --from=builder /install /usr/local
COPY --from=builder /usr/lib /usr/lib
WORKDIR /
EXPOSE 80
CMD ["gunicorn", "--bind", "0.0.0.0:80", "buildings_api:build_app()"]
