
DROP TABLE IF EXISTS buildings CASCADE;
DROP TABLE IF EXISTS accounts_google CASCADE;
DROP TABLE IF EXISTS accounts_standard CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TYPE IF EXISTS hash_gen CASCADE;
